build-mingw.yml: revert

diff --git a/.github/workflows/build-mingw.yml b/.github/workflows/build-mingw.yml
--- a/.github/workflows/build-mingw.yml
+++ b/.github/workflows/build-mingw.yml
@@ -175,10 +175,10 @@ jobs:
             --enable-web-progs  --enable-synctex \
             --disable-mf  --disable-mf-nowin \
             --disable-etex  --disable-etex-synctex \
-            --enable-aleph \
+            --disable-aleph \
             --disable-luatex  --disable-luajittex  --disable-luahbtex  --disable-luajithbtex \
             --enable-xetex  --enable-xetex-synctex \
-            --enable-mflua  --disable-mflua-nowin  --enable-mfluajit  --disable-mfluajit-nowin \
+            --disable-mflua  --disable-mflua-nowin  --disable-mfluajit  --disable-mfluajit-nowin \
             --disable-epsfwin  --disable-hp2627win  --disable-mftalkwin  --disable-nextwin \
             --disable-regiswin  --disable-suntoolswin  --disable-tektronixwin  --disable-unitermwin \
             --disable-missing \
@@ -307,13 +307,13 @@ jobs:
           echo -e "###\n### link without libtool  xetex.exe\n###"
           g++  -g -O2   -o xetex.exe xetexdir/xetex-xetexextra.o synctexdir/xetex-synctex.o xetex-xetexini.o xetex-xetex0.o xetex-xetex-pool.o libxetex.a /d/a/texlive-source/texlive-source/Work/libs/harfbuzz/libharfbuzz.a /d/a/texlive-source/texlive-source/Work/libs/graphite2/libgraphite2.a -L/mingw64/lib -licuin -licuuc -licudt -lpthread -lm     /d/a/texlive-source/texlive-source/Work/libs/teckit/libTECkit.a /d/a/texlive-source/texlive-source/Work/libs/libpng/libpng.a /d/a/texlive-source/texlive-source/Work/libs/freetype2/libfreetype.a /d/a/texlive-source/texlive-source/Work/libs/pplib/libpplib.a /d/a/texlive-source/texlive-source/Work/libs/zlib/libz.a libmd5.a -lfontconfig -lfreetype lib/lib.a /d/a/texlive-source/texlive-source/Work/texk/kpathsea/.libs/libkpathsea.a -lwsock32 || echo -e "**\n** fail to link xetex.exe"
 
-          make wofm2opl.exe || echo "fail to make wofm2opl.exe"
-          make wopl2ofm.exe || echo "fail to make wopl2ofm.exe"
-          make wovf2ovp.exe || echo "fail to make wovf2ovp.exe"
-          make wovp2ovf.exe || echo "fail to make wovp2ovf.exe"
-          make odvicopy.exe || echo "fail to make odvicopy.exe"
-          make odvitype.exe || echo "fail to make odvitype.exe"
-          make otangle.exe  || echo "fail to make otangle.exe"
+          # make wofm2opl.exe || echo "fail to make wofm2opl.exe"
+          # make wopl2ofm.exe || echo "fail to make wopl2ofm.exe"
+          # make wovf2ovp.exe || echo "fail to make wovf2ovp.exe"
+          # make wovp2ovf.exe || echo "fail to make wovp2ovf.exe"
+          # make odvicopy.exe || echo "fail to make odvicopy.exe"
+          # make odvitype.exe || echo "fail to make odvitype.exe"
+          # make otangle.exe  || echo "fail to make otangle.exe"
 
           # make luatex.exe      || echo "fail to make luatex.exe"
           # make luajittex.exe   || echo "fail to make luajittex.exe"
@@ -324,8 +324,8 @@ jobs:
 
           make synctex.exe || echo "fail to make synctex.exe"
 
-          make mflua.exe       || echo "fail to make mflua.exe"
-          make mfluajit.exe    || echo "fail to make mfluajit.exe"
+          # make mflua.exe       || echo "fail to make mflua.exe"
+          # make mfluajit.exe    || echo "fail to make mfluajit.exe"
 
           cd ./omegafonts
           make omfonts.exe || echo "fail to make omfonts.exe"
@@ -406,7 +406,7 @@ jobs:
           echo ""
           ./aleph.exe --version    || echo "aleph"
           echo ""
-          ./synctex.exe help       || echo "synctex"
+          ./synctex.exe --version || echo "synctex"
           echo ""
           ./mflua.exe --version    || echo "mflua"
           ./mfluajit.exe --version || echo "mfluajit"
@@ -570,18 +570,15 @@ jobs:
 #          $srcdir/luatexdir/luajittex.test      || echo -e "**\n** failed: luatexdir/luajittex.test\n**"
 #          $srcdir/luatexdir/luajitimage.test    || echo -e "**\n** failed: luatexdir/luajitimage.test\n**"
 #          echo ""
-          $srcdir/alephdir/aleph.test           || echo -e "**\n** failed: alephdir/aleph.test\n**"
-          echo ""
-          $srcdir/synctexdir/synctex.test       || echo -e "**\n** failed: synctexdir/synctex.test\n**"
-          echo ""
-          $srcdir/mfluadir/mfluatraptest.test   || echo -e "**\n** failed: mfluadir/mfluatraptest.test\n**"
-          $srcdir/mfluajitdir/mfluajittraptest.test   || echo -e "**\n** failed: mfluajitdir/mfluajittraptest.test\n**"
-          echo ""
-          $srcdir/libmd5/md5.test               || echo -e "**\n** failed: libmd5/md5.test\n**"
+#          $srcdir/alephdir/aleph.test           || echo -e "**\n** failed: alephdir/aleph.test\n**"
+#          echo ""
+#          $srcdir/synctexdir/synctex.test       || echo -e "**\n** failed: synctexdir/synctex.test\n**"
+#          echo ""
+#          $srcdir/mfluadir/mfluatraptest.test   || echo -e "**\n** failed: mfluadir/mfluatraptest.test\n**"
+#          $srcdir/mfluajitdir/mfluajittraptest.test   || echo -e "**\n** failed: mfluajitdir/mfluajittraptest.test\n**"
         env:
           srcdir: "../../../texk/web2c"
           TEXMFCNF: "../../../texk/kpathsea"
-          LN_S: "cp"
 
       - name: web2c triptest
         shell: msys2 {0}
