build-*.yml: --enable-pdftex

diff --git a/.github/workflows/build-mingw.yml b/.github/workflows/build-mingw.yml
--- a/.github/workflows/build-mingw.yml
+++ b/.github/workflows/build-mingw.yml
@@ -193,14 +193,14 @@ jobs:
             --enable-eptex \
             --enable-uptex \
             --enable-euptex \
-            --disable-pmp \
-            --disable-upmp \
+            --enable-pmp \
+            --enable-upmp \
             --enable-ptex-synctex \
             --enable-eptex-synctex \
             --enable-uptex-synctex \
             --enable-euptex-synctex \
-            --disable-pdftex \
-            --disable-pdftex-synctex \
+            --enable-pdftex \
+            --enable-pdftex-synctex \
             --disable-mf \
             --disable-mf-nowin \
             --enable-tex \
@@ -310,8 +310,9 @@ jobs:
           # make upmp.p
           # make upmp.c
           # make upmp.exe
-          # make pmpopst.exe || echo "fail to make pmpopst.exe"
-          # make upmpopst.exe || echo "fail to make upmpopst.exe"
+          make pmpopst.exe || echo "fail to make pmpopst.exe"
+          make upmpopst.exe || echo "fail to make upmpopst.exe"
+          make pdftex.exe || echo "fail to make pdftex.exe"
           echo "!!! make complete !!!"
 
       - name: web2c version check
@@ -369,6 +370,12 @@ jobs:
           ./pktype.exe --version || echo "pktype"
           echo ""
           ./pooltype.exe --version || echo "pooltype"
+          echo ""
+          ./pmpost.exe --version || echo "pmpost"
+          echo ""
+          ./upmpost.exe --version || echo "upmpost"
+          echo ""
+          ./pdftex.exe --version || echo "pdftex"
         env:
           TEXMFCNF: "../../../texk/kpathsea"
 
