build-mingw.yml: chcp.com

diff --git a/.github/workflows/build-mingw.yml b/.github/workflows/build-mingw.yml
--- a/.github/workflows/build-mingw.yml
+++ b/.github/workflows/build-mingw.yml
@@ -554,23 +554,21 @@ jobs:
           srcdir: "../../../texk/web2c"
           TEXMFCNF: "../../../texk/kpathsea"
 
-      - name: set codepage CP932 (Japanese)
+      - name: web2c check CP932 (Japanese)
+        shell: msys2 {0}
         run: |
-          chcp 932
-          cd .\Work\texk\web2c
-          bash ..\..\..\texk\web2c\ptexdir\wcfname.test
-          bash ..\..\..\texk\web2c\uptexdir\wcfname.test
-          bash ..\..\..\texk\web2c\eptexdir\wcfname.test
-          bash ..\..\..\texk\web2c\euptexdir\wcfname.test
-          bash ..\..\..\texk\web2c\pdftexdir\wcfname.test
-          bash ..\..\..\texk\web2c\xetexdir\wcfname.test
+          cd ./Work/texk/web2c
+          chcp.com
+          chcp.com 932
+          $srcdir/ptexdir/wcfname.test          || echo -e "**\n** failed: ptexdir/wcfname.test\n**"
+          $srcdir/uptexdir/wcfname.test         || echo -e "**\n** failed: uptexdir/wcfname.test\n**"
+          $srcdir/eptexdir/wcfname.test         || echo -e "**\n** failed: eptexdir/wcfname.test\n**"
+          $srcdir/euptexdir/wcfname.test        || echo -e "**\n** failed: euptexdir/wcfname.test\n**"
+          $srcdir/pdftexdir/wcfname.test        || echo -e "**\n** failed: pdftexdir/wcfname.test\n**"
+          $srcdir/xetexdir/wcfname.test         || echo -e "**\n** failed: xetexdir/wcfname.test\n**"
         env:
           srcdir: "../../../texk/web2c"
           TEXMFCNF: "../../../texk/kpathsea"
-
-      - name: check codepage
-        run: |
-          chcp
 
       #- name: ttf2pk2
       #  shell: msys2 {0}
