web2c/*ptexdir/*.test: add

diff --git a/.github/workflows/build-msvc.yml b/.github/workflows/build-msvc.yml
--- a/.github/workflows/build-msvc.yml
+++ b/.github/workflows/build-msvc.yml
@@ -243,10 +243,10 @@ jobs:
           ./uptex.exe --version || echo "uptex"
           echo ""
           ls -lR
-          #echo ""
-          #./eptex.exe --version || echo "eptex"
-          #echo ""
-          #./euptex.exe --version || echo "euptex"
+          echo ""
+          ./eptex.exe --version || echo "eptex"
+          echo ""
+          ./euptex.exe --version || echo "euptex"
           #echo ""
           #./updvitype.exe --version || echo "updvitype"
           #echo ""
@@ -266,11 +266,30 @@ jobs:
           # $srcdir/cwebdir/cweave.test || echo -e "**\n** failed: cweave.test\n**"
           $srcdir/tiedir/tie.test       || echo -e "**\n** failed: tie.test\n**"
           $srcdir/tangle.test           || echo -e "**\n** failed: tangle.test\n**"
-          $srcdir/ptexdir/pver.test     || echo -e "**\n** failed: pver.test\n**"
-          # $srcdir/eptexdir/epver.test   || echo -e "**\n** failed: epver.test\n**"
-          $srcdir/uptexdir/upver.test   || echo -e "**\n** failed: upver.test\n**"
-          $srcdir/uptexdir/upkcat.test  || echo -e "**\n** failed: upkcat.test\n**"
-          # $srcdir/eputexdir/eupver.test || echo -e "**\n** failed: eupver.test\n**"
+
+          $srcdir/ptexdir/ptriptest.test   || echo -e "**\n** failed: p/ptriptest.test\n**"
+          $srcdir/ptexdir/pver.test        || echo -e "**\n** failed: p/pver.test\n**"
+          $srcdir/ptexdir/wcfname.test     || echo -e "**\n** failed: p/wcfname.test\n**"
+
+          $srcdir/uptexdir/uptriptest.test || echo -e "**\n** failed: up/uptriptest.test\n**"
+          $srcdir/uptexdir/ptriptest.test  || echo -e "**\n** failed: up/ptriptest.test\n**"
+          $srcdir/uptexdir/upver.test      || echo -e "**\n** failed: up/upver.test\n**"
+          $srcdir/uptexdir/upkcat.test     || echo -e "**\n** failed: up/upkcat.test\n**"
+          $srcdir/uptexdir/wcfname.test    || echo -e "**\n** failed: up/wcfname.test\n**"
+          $srcdir/uptexdir/wcfname0.test   || echo -e "**\n** failed: up/wcfname0.test\n**"
+
+          $srcdir/eptexdir/eptriptest.test   || echo -e "**\n** failed: ep/eptriptest.test\n**"
+          $srcdir/eptexdir/pdfprimitive.test || echo -e "**\n** failed: ep/pdfprimitive.test\n**"
+          $srcdir/eptexdir/epver.test        || echo -e "**\n** failed: ep/epver.test\n**"
+          $srcdir/eptexdir/wcfname.test      || echo -e "**\n** failed: ep/wcfname.test\n**"
+
+          $srcdir/euptexdir/euptriptest.test  || echo -e "**\n** failed: eup/euptriptest.test\n**"
+          $srcdir/euptexdir/eptriptest.test   || echo -e "**\n** failed: eup/eptriptest.test\n**"
+          $srcdir/euptexdir/pdfprimitive.test || echo -e "**\n** failed: eup/pdfprimitive.test\n**"
+          $srcdir/euptexdir/eupver.test       || echo -e "**\n** failed: eup/eupver.test\n**"
+          $srcdir/euptexdir/wcfname.test      || echo -e "**\n** failed: eup/wcfname.test\n**"
+          $srcdir/euptexdir/wcfname0.test     || echo -e "**\n** failed: eup/wcfname0.test\n**"
+
         env:
           srcroot: ".."
           TEXMFCNF: "../texk/kpathsea/tests/windows"
