build-mingw.yml: separate pTeX & upTeX

diff --git a/.github/workflows/build-mingw.yml b/.github/workflows/build-mingw.yml
--- a/.github/workflows/build-mingw.yml
+++ b/.github/workflows/build-mingw.yml
@@ -554,21 +554,44 @@ jobs:
           srcdir: "../../../texk/web2c"
           TEXMFCNF: "../../../texk/kpathsea"
 
-      - name: web2c check CP932 (Japanese)
+      - name: web2c check pTeX
         shell: msys2 {0}
         run: |
           cd ./Work/texk/web2c
           chcp.com
+          $srcdir/ptexdir/wcfname.test          || echo -e "**\n** failed: ptexdir/wcfname.test\n**"
+          $srcdir/uptexdir/wcfname1.test        || echo -e "**\n** failed: uptexdir/wcfname1.test\n**"
+          $srcdir/eptexdir/wcfname.test         || echo -e "**\n** failed: eptexdir/wcfname.test\n**"
+          $srcdir/euptexdir/wcfname1.test       || echo -e "**\n** failed: euptexdir/wcfname1.test\n**"
           chcp.com 932
           $srcdir/ptexdir/wcfname.test          || echo -e "**\n** failed: ptexdir/wcfname.test\n**"
-          $srcdir/uptexdir/wcfname.test         || echo -e "**\n** failed: uptexdir/wcfname.test\n**"
+          $srcdir/uptexdir/wcfname1.test        || echo -e "**\n** failed: uptexdir/wcfname1.test\n**"
           $srcdir/eptexdir/wcfname.test         || echo -e "**\n** failed: eptexdir/wcfname.test\n**"
-          $srcdir/euptexdir/wcfname.test        || echo -e "**\n** failed: euptexdir/wcfname.test\n**"
+          $srcdir/euptexdir/wcfname1.test       || echo -e "**\n** failed: euptexdir/wcfname1.test\n**"
+        env:
+          srcdir: "../../../texk/web2c"
+          TEXMFCNF: "../../../texk/kpathsea"
+          guess_input_kanji_encoding: "1"
+          command_line_encoding: "none"
+
+      - name: web2c check upTeX
+        shell: msys2 {0}
+        run: |
+          cd ./Work/texk/web2c
+          chcp.com
+          $srcdir/uptexdir/wcfname2.test        || echo -e "**\n** failed: uptexdir/wcfname2.test\n**"
+          $srcdir/euptexdir/wcfname2.test       || echo -e "**\n** failed: euptexdir/wcfname2.test\n**"
+          $srcdir/pdftexdir/wcfname.test        || echo -e "**\n** failed: pdftexdir/wcfname.test\n**"
+          $srcdir/xetexdir/wcfname.test         || echo -e "**\n** failed: xetexdir/wcfname.test\n**"
+          chcp.com 932
+          $srcdir/uptexdir/wcfname2.test        || echo -e "**\n** failed: uptexdir/wcfname2.test\n**"
+          $srcdir/euptexdir/wcfname2.test       || echo -e "**\n** failed: euptexdir/wcfname2.test\n**"
           $srcdir/pdftexdir/wcfname.test        || echo -e "**\n** failed: pdftexdir/wcfname.test\n**"
           $srcdir/xetexdir/wcfname.test         || echo -e "**\n** failed: xetexdir/wcfname.test\n**"
         env:
           srcdir: "../../../texk/web2c"
           TEXMFCNF: "../../../texk/kpathsea"
+          command_line_encoding: "utf-8"
 
       #- name: ttf2pk2
       #  shell: msys2 {0}
