build-mingw.yml: --enable-aleph

diff --git a/.github/workflows/build-mingw.yml b/.github/workflows/build-mingw.yml
--- a/.github/workflows/build-mingw.yml
+++ b/.github/workflows/build-mingw.yml
@@ -157,7 +157,7 @@ jobs:
             --enable-web-progs  --enable-synctex \
             --enable-mf  --enable-mf-nowin \
             --disable-etex  --disable-etex-synctex \
-            --disable-aleph \
+            --enable-aleph \
             --enable-luatex  --enable-luajittex  --enable-luahbtex  --enable-luajithbtex \
             --enable-xetex  --enable-xetex-synctex \
             --disable-mflua  --disable-mflua-nowin  --disable-mfluajit  --disable-mfluajit-nowin \
@@ -270,6 +270,8 @@ jobs:
           make luahbtex.exe    || echo "fail to make luahbtex.exe"
           make luajithbtex.exe || echo "fail to make luajithbtex.exe"
 
+          make aleph.exe       || echo "fail to make aleph.exe"
+
           echo "!!! make complete !!!"
 
       - name: web2c version check
@@ -356,7 +358,9 @@ jobs:
           echo ""
           ./odvitype.exe --version || echo "odvitype"
           echo ""
-          ./otangle.exe --version || echo "otangle"
+          ./otangle.exe --version  || echo "otangle"
+          echo ""
+          ./aleph.exe --version    || echo "aleph"
           echo ""
           ls -l ./*.exe
         env:
@@ -490,6 +494,8 @@ jobs:
           $srcdir/luatexdir/luaimage.test       || echo -e "**\n** failed: luatexdir/luaimage.test\n**"
           $srcdir/luatexdir/luajittex.test      || echo -e "**\n** failed: luatexdir/luajittex.testn**"
           $srcdir/luatexdir/luajitimage.test    || echo -e "**\n** failed: luatexdir/luajitimage.test"
+          echo ""
+          $srcdir/alephdir/aleph.test           || echo -e "**\n** failed: alephdir/aleph.test\n**"
           echo ""
           $srcdir/synctexdir/synctex.test       || echo -e "**\n** failed: synctexdir/synctex.test\n**"
         env:
