build-mingw.yml: update

diff --git a/.github/workflows/build-mingw.yml b/.github/workflows/build-mingw.yml
--- a/.github/workflows/build-mingw.yml
+++ b/.github/workflows/build-mingw.yml
@@ -145,7 +145,34 @@ jobs:
         run: |
           mkdir ./Work/texk
           cd ./Work/texk
-          for prog in kpathsea ptexenc web2c afm2pl bibtex-x chktex cjkutils detex dtl dvi2tty dvidvi dviljk dviout-util dvipdfm-x dvipng dvipos dvipsk gregorio gsftopk lcdf-typetools makeindexk makejvf mendexk musixtnt ps2pk psutils seetexk tex4htk ttfdump upmendex texlive; do \
+          export run_stdio_test=0
+
+          for prog in kpathsea ptexenc; do \
+            mkdir $prog; \
+            cd $prog; \
+            ../../../texk/$prog/configure \
+                 || echo -e "**\n** failed: configure $prog\n**"; \
+            make || echo -e "**\n** failed: make $prog\n**"; \
+            make check || echo -e "**\n** failed: make check $prog\n**"; \
+            cd ..; \
+          done
+
+          prog=web2c
+            mkdir $prog
+            cd $prog
+            ../../../texk/$prog/configure \
+              --without-x \
+              --with-system-pixman \
+              --with-system-cairo \
+              --with-system-gmp \
+              --with-system-mpfr \
+              --with-system-icu \
+                 || echo -e "**\n** failed: configure $prog\n**"
+            make || echo -e "**\n** failed: make $prog\n**"
+            make check || echo -e "**\n** failed: make check $prog\n**"
+            cd ..
+
+          for prog in afm2pl bibtex-x chktex cjkutils detex dtl dvi2tty dvidvi dviljk dviout-util dvipdfm-x dvipng dvipos dvipsk gregorio gsftopk lcdf-typetools makeindexk makejvf mendexk musixtnt ps2pk psutils seetexk tex4htk ttfdump upmendex texlive; do \
             mkdir $prog; \
             cd $prog; \
             ../../../texk/$prog/configure \
@@ -158,5 +185,7 @@ jobs:
             make check || echo -e "**\n** failed: make check $prog\n**"; \
             cd ..; \
           done
+          echo -e "**\n** dvidvi.log::"
+          cat dvidvi.log
 
       - run: echo "⛄ This job's status is ${{ job.status }}."
