build-*.yml: disable mf etc

diff --git a/.github/workflows/build-mingw.yml b/.github/workflows/build-mingw.yml
--- a/.github/workflows/build-mingw.yml
+++ b/.github/workflows/build-mingw.yml
@@ -311,6 +311,10 @@ jobs:
           make pktogf.exe
           make pktype.exe
           make pooltype.exe
+          make tftopl.exe || echo "fail to make tftopl.exe"
+          make vftovp.exe || echo "fail to make vftovp.exe"
+          make vptovf.exe || echo "fail to make vptovf.exe"
+          make weave.exe || echo "fail to make weave.exe"
           # make pmp.web
           # make pmp.p
           # make pmp.c
@@ -323,6 +327,8 @@ jobs:
           make upmpopst.exe || echo "fail to make upmpopst.exe"
           make pdftex.exe || echo "fail to make pdftex.exe"
           make mf.exe || echo "fail to make mf.exe"
+          make hitex.exe || echo "fail to make hitex.exe"
+          make synctex.exe || echo "fail to make synctex.exe"
           echo "!!! make complete !!!"
 
       - name: web2c version check
@@ -389,6 +395,10 @@ jobs:
           echo ""
           ./mf.exe --version || echo "mf"
           echo ""
+          ./synctex.exe --version || echo "synctex"
+          echo ""
+          ./hitex.exe --version || echo "hitex"
+          echo ""
           ls -l ./*.exe
         env:
           TEXMFCNF: "../../../texk/kpathsea"
@@ -430,6 +440,16 @@ jobs:
           echo ""
           $srcdir/pooltype.test       || echo -e "**\n** failed: pooltype.test\n**"
           echo ""
+
+          $srcdir/tftopl.test         || echo -e "**\n** failed: tftopl.test\n**"
+          echo ""
+          $srcdir/vftovp.test         || echo -e "**\n** failed: vftovp.test\n**"
+          echo ""
+          $srcdir/vptovf.test         || echo -e "**\n** failed: vptovf.test\n**"
+          echo ""
+          $srcdir/weave.test          || echo -e "**\n** failed: weave.test\n**"
+          echo ""
+
           $srcdir/tangle.test         || echo -e "**\n** failed: tangle.test\n**"
           echo ""
           $srcdir/twill.test          || echo -e "**\n** failed: twill.test\n**"
@@ -459,34 +479,66 @@ jobs:
           echo ""
           # $srcdir/uptexdir/upbibtex-mem.test  || echo -e "**\n** failed: upbibtex-mem.test\n**"
           # echo ""
+
+          $srcdir/uptexdir/upbibtex-openout-test.pl  || echo -e "**\n** failed: upbibtex-openout-test.pl\n**"
+          $srcdir/uptexdir/upbibtex-longline-test.pl || echo -e "**\n** failed: upbibtex-longline-test.pl\n**"
+          $srcdir/uptexdir/nissya.test    || echo -e "**\n** failed: nissya.test\n**"
+          $srcdir/uptexdir/skipjfmp.test  || echo -e "**\n** failed: skipjfmp.test\n**"
+          $srcdir/uptexdir/newjfm.test    || echo -e "**\n** failed: newjfm.test\n**"
+          $srcdir/uptexdir/uparse.test    || echo -e "**\n** failed: uparse.test\n**"
+          $srcdir/uptexdir/gkhuge.test    || echo -e "**\n** failed: gkhuge.test\n**"
+
           export abs_srcdir=../$srcdir
           $srcdir/mftraptest.test            || echo -e "**\n** failed: mftraptest.test\n**"
           echo ""
           $srcdir/triptest.test              || echo -e "**\n** failed: triptest.test\n**"
           echo ""
-          $srcdir/etexdir/etriptest.test     || echo -e "**\n** failed: etriptest.test\n**"
+          $srcdir/etexdir/etriptest.test     || echo -e "**\n** failed: etexdir/etriptest.test\n**"
           echo ""
-          $srcdir/eptexdir/pdfprimitive.test || echo -e "**\n** failed: pdfprimitive.test\n**"
+          $srcdir/eptexdir/pdfprimitive.test || echo -e "**\n** failed: eptexdir/pdfprimitive.test\n**"
           echo ""
-          $srcdir/ptexdir/ptriptest.test     || echo -e "**\n** failed: ptriptest.test\n**"
+          $srcdir/ptexdir/ptriptest.test     || echo -e "**\n** failed: ptexdir/ptriptest.test\n**"
           echo ""
-          $srcdir/uptexdir/ptriptest.test    || echo -e "**\n** failed: ptriptest.test\n**"
+          $srcdir/uptexdir/ptriptest.test    || echo -e "**\n** failed: uptexdir/ptriptest.test\n**"
           echo ""
-          $srcdir/uptexdir/ptriptest.test    || echo -e "**\n** failed: ptriptest.test\n**"
+          $srcdir/uptexdir/uptriptest.test   || echo -e "**\n** failed: uptexdir/uptriptest.test\n**"
           echo ""
-          $srcdir/uptexdir/uptriptest.test   || echo -e "**\n** failed: uptriptest.test\n**"
+          $srcdir/eptexdir/eptriptest.test   || echo -e "**\n** failed: eptexdir/eptriptest.test\n**"
           echo ""
-          $srcdir/eptexdir/eptriptest.test   || echo -e "**\n** failed: eptriptest.test\n**"
+          $srcdir/euptexdir/euptriptest.test || echo -e "**\n** failed: euptexdir/euptriptest.test\n**"
           echo ""
-          $srcdir/euptexdir/euptriptest.test || echo -e "**\n** failed: euptriptest.test\n**"
+          $srcdir/ptexdir/wcfname.test       || echo -e "**\n** failed: ptexdir/wcfname.test\n**"
+          $srcdir/uptexdir/wcfname.test      || echo -e "**\n** failed: uptexdir/wcfname.test\n**"
+          $srcdir/eptexdir/wcfname.test      || echo -e "**\n** failed: eptexdir/wcfname.test\n**"
+          $srcdir/euptexdir/wcfname.test     || echo -e "**\n** failed: euptexdir/wcfname.test\n**"
           echo ""
           $srcdir/tests/tex-closeout.test    || echo -e "**\n** failed: tex-closeout.test\n**"
+          echo ""
+          $srcdir/tests/bibtex.test          || echo -e "**\n** failed: bibtex.test\n**"
           echo ""
           $srcdir/tests/bibtex-auxinclude.test || echo -e "**\n** failed: bibtex-auxinclude.test\n**"
           echo ""
           $srcdir/tests/bibtex-bigauth.test  || echo -e "**\n** failed: bibtex-bigauth.test\n**"
           echo ""
-          $srcdir/tests/bibtex-mem.test      || echo -e "**\n** failed: bibtex-mem.test\n**"
+          # $srcdir/tests/bibtex-mem.test      || echo -e "**\n** failed: bibtex-mem.test\n**"
+          # echo ""
+          $srcdir/tests/bibtex-openout-test.pl  || echo -e "**\n** failed: bibtex-openout-test.pl\n**"
+          echo ""
+          $srcdir/tests/bibtex-longline-test.pl || echo -e "**\n** failed: bibtex-longline-test.pl\n**"
+          echo ""
+          $srcdir/hitexdir/tests/hello.test    || echo -e "**\n** failed: hitex hello.test\n**"
+          $srcdir/hitexdir/tests/rule.test     || echo -e "**\n** failed: hitex rule.test\n**"
+          echo ""
+          $srcdir/pdftexdir/wprob.test          || echo -e "**\n** failed: pdftexdir/wprob.test\n**"
+          $srcdir/pdftexdir/pdftex.test         || echo -e "**\n** failed: pdftexdir/pdftex.test\n**"
+          $srcdir/pdftexdir/pdfimage.test       || echo -e "**\n** failed: pdftexdir/pdfimage.test\n**"
+          $srcdir/pdftexdir/expanded.test       || echo -e "**\n** failed: pdftexdir/expanded.test\n**"
+          $srcdir/pdftexdir/tests/cnfline.test  || echo -e "**\n** failed: pdftexdir/tests/cnfline.test\n**"
+          $srcdir/pdftexdir/tests/partoken.test || echo -e "**\n** failed: pdftexdir/tests/partoken.test\n**"
+          $srcdir/pdftexdir/wcfname.test        || echo -e "**\n** failed: pdftexdir/wcfname.test\n**"
+          $srcdir/pdftexdir/ttf2afm.test        || echo -e "**\n** failed: pdftexdir/ttf2afm.test\n**"
+          $srcdir/pdftexdir/pdftosrc.test       || echo -e "**\n** failed: pdftexdir/pdftosrc.test\n**"
+          $srcdir/synctexdir/synctex.test       || echo -e "**\n** failed: synctexdir/synctex.test\n**"
         env:
           srcdir: "../../../texk/web2c"
           TEXMFCNF: "../../../texk/kpathsea"
