build-mingw.yml: build luatex

diff --git a/.github/workflows/build-mingw.yml b/.github/workflows/build-mingw.yml
--- a/.github/workflows/build-mingw.yml
+++ b/.github/workflows/build-mingw.yml
@@ -158,7 +158,7 @@ jobs:
             --enable-mf  --enable-mf-nowin \
             --disable-etex  --disable-etex-synctex \
             --disable-aleph \
-            --disable-luatex  --disable-luajittex  --disable-luahbtex  --disable-luajithbtex \
+            --enable-luatex  --enable-luajittex  --enable-luahbtex  --enable-luajithbtex \
             --enable-xetex  --enable-xetex-synctex \
             --disable-mflua  --disable-mflua-nowin  --disable-mfluajit  --disable-mfluajit-nowin \
             --disable-epsfwin  --disable-hp2627win  --disable-mftalkwin  --disable-nextwin \
@@ -264,6 +264,11 @@ jobs:
           make odvicopy.exe || echo "fail to make odvicopy.exe"
           make odvitype.exe || echo "fail to make odvitype.exe"
           make otangle.exe  || echo "fail to make otangle.exe"
+
+          make luatex.exe      || echo "fail to make luatex.exe"
+          make luajittex.exe   || echo "fail to make luajittex.exe"
+          make luahbtex.exe    || echo "fail to make luahbtex.exe"
+          make luajithbtex.exe || echo "fail to make luajithbtex.exe"
 
           echo "!!! make complete !!!"
 
@@ -480,6 +485,11 @@ jobs:
           $srcdir/omegaware/version.test        || echo -e "**\n** failed: omegaware/version.test\n**"
           $srcdir/omegaware/vrepeat.test        || echo -e "**\n** failed: omegaware/vrepeat.test\n**"
           $srcdir/omegaware/yannis.test         || echo -e "**\n** failed: omegaware/yannis.test\n**"
+          echo ""
+          $srcdir/luatexdir/luatex.test         || echo -e "**\n** failed: luatexdir/luatex.test\n**"
+          $srcdir/luatexdir/luaimage.test       || echo -e "**\n** failed: luatexdir/luaimage.test\n**"
+          $srcdir/luatexdir/luajittex.test      || echo -e "**\n** failed: luatexdir/luajittex.testn**"
+          $srcdir/luatexdir/luajitimage.test    || echo -e "**\n** failed: luatexdir/luajitimage.test"
           echo ""
           $srcdir/synctexdir/synctex.test       || echo -e "**\n** failed: synctexdir/synctex.test\n**"
         env:
